name: Deploy Lambda to S3

on:
  push:
    branches:
      - lambdas-raf  # Trigger the workflow on pushes to the `lambdas-raf` branch

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3


        # Step 2: Configure AWS credentials using OIDC
    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::122610483522:role/github_actions_lambda_deploy_role
        aws-region: us-east-1 # Replace with your AWS region if needed

    # Step 3: Zip the Lambda code
    - name: Zip Lambda Code
      run: |
        mkdir -p build
        zip -j build/lambda.zip src/lambda/index.js
  
    
    # Step 4: Zip the Lambda layer
    - name: Zip Lambda Layer
      run: |
        mkdir -p build
        zip -r build/layer.zip src/lambda/nodejs
 

    # Step 5: Upload to S3
    - name: Upload to S3
      run: |
        aws s3 cp build/lambda.zip s3://rcgrafbucket/lambda.zip

    # Step 6: Upload Layer to S3
    - name: Upload to S3
      run: |
        aws s3 cp build/layer.zip s3://rcgrafbucket/layer.zip

